spring:
  application:
    name: sleep
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://3.36.58.102:3306/dance?serverTimezone=UTC&characterEncoding=UTF-8
    username: dance
    password: dance1234
  jpa:
    hibernate:
      ddl-auto: update
    hikari:
      idle-timeout: 300
      max-lifetime: 300
    properties:
      hibernate:
        format_sql: true

    show_sql: true
    defer-datasource-initialization: true
    sql:
      init:
        mode: always
    output:
      ansi.enabled: always
    servlet:
      multipart:
        max-file-size: 50MB
        max-request-size: 50MB
  cache:
    type: redis
  redis:
    host: 13.124.215.149
    port: 6000
    password: b1234

server:
  port: 8089

jwt:
  secret: Tkxkfgkrpgownjwlqdprkrhtlvekwhfflek

#security:
#  db:
#    aes:
#      private-key: MALANGMALANGZOOFLIXA203FERYAKGOV
#  api:
#    aes:
#      private-key: ZOOFLIXAESMALANG203FFSTEWMDFKHOT

cloud:
  aws:
    s3:
      bucket: ssafy2024-dance
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      access-key: AKIARHUMYOL6QNGDFPG6
      secret-key: 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